services:
  db:
    image: postgres:latest
    restart: always
    container_name: sbs
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sbs
    ports:
      - '5432:5432'